# default config

task: eval

debug: False
wandb_mode: online
seed: 0

engine:
  name: DDPEngine
  backend: nccl

bandit_algo_list: null
      
data_sampler:
  name: StatlogDataSampler
  file_name: /data/ContextualBandits/raw/statlog.trn
  dim_context: 9
  num_arms: 7
  num_contexts: -1
  shuffle_rows: True
  remove_underrepresented: True

bandit_env:
  name: BaseBanditEnv

evaluator:
  name: BaseEvaluator
  num_exp: 1
  num_steps: 25000
