# default config

task: eval

debug: False
wandb_mode: online
seed: 0

engine:
  name: DDPEngine
  backend: nccl

bandit_algo_list: null

data_sampler:
  name: AdultDataSampler
  file_name: /data/ContextualBandits/raw/adult.data
  dim_context: 92
  num_arms: 14
  num_contexts: -1
  shuffle_rows: True
  remove_underrepresented: True

bandit_env:
  name: BaseBanditEnv

evaluator:
  name: BaseEvaluator
  num_exp: 1
  num_steps: 25000
