# default config

task: eval

debug: False
wandb_mode: online
seed: 0

engine:
  name: DDPEngine
  backend: nccl

bandit_algo_list: null

data_sampler:
  name: R6DataSampler
  raw_dir: /data/R6NewsRecommendation/raw
  processed_dir: /home/junhyun/data/R6NewsRecommendation/processed
  num_contexts: 2778
  day: [1,2,3,4,5,6,7,8,9]
  reward_balance: -1

bandit_env:
  name: R6BanditEnv
  dim_context: 12

evaluator:
  name: R6Evaluator
  num_exp: 1
  num_steps: -1
  learn_ratio: 0.9
  plot_comparison_shape: bar
